-- CRIACAO DE INDICES / UNIQUE KEYS

ALTER TABLE COLABORADOR 
ADD CONSTRAINT EMAIL_UNIQUE UNIQUE (EMAIL);

CREATE INDEX INDICE_COLABORADOR ON COLABORADOR (ID_PERMISSAO);

CREATE INDEX INDICE_FEITO ON FEITO(ID_PERMISSAO);

CREATE INDEX INDICE_COLABORADOR_FEITO ON COLABORADOR_FEITO (ID_COLABORADOR,ID_FEITO);

CREATE INDEX INDICE_SOLICITACAO_ACESSO ON SOLICITACAO_ACESSO(ID_COLABORADOR);

CREATE INDEX INDICE_TIMECWI_COLABORADOR ON TIMECWI_COLABORADOR(ID_TIMECWI,ID_COLABORADOR);

CREATE INDEX INDICE_COLABORADOR_TAG ON COLABORADOR_TAG (ID_COLABORADOR);

CREATE INDEX INDICE_COLABORADOR_REACAO_TAG ON COLABORADOR_REACAO_TAG (ID_COLABORADORTAG,ID_COLABORADOR);