CREATE TABLE PERMISSAO ( 
    ID NUMBER(12) NOT NULL,
	DESCRICAO VARCHAR2(20) NOT NULL,
    CONSTRAINT PERMISSAO_PK PRIMARY KEY (ID)
);

CREATE TABLE COLABORADOR ( 
    ID NUMBER(12) NOT NULL,
    EMAIL VARCHAR2(100) NOT NULL,
	NOMECOMPLETO VARCHAR2(100) NOT NULL,	
    NASCIMENTO DATE NOT NULL,
    ADMISSAO DATE NOT NULL,
    DEMISSAO DATE NULL,
    SEDE NUMBER(1) NOT NULL, -- 0 SL, 1 SP, 2 POA
	RAMAL VARCHAR2(10) NULL, 
    ANDAR VARCHAR2(10) NULL,
    POSICAO VARCHAR2(10) NULL,
    DESCRICAO VARCHAR2(200) NULL,
    DESCRICAORESUMIDA VARCHAR2(20) NULL,
    ID_PERMISSAO NUMBER(12) NOT NULL, -- PERMISSAO: ADMIN, COLABORADOR, MASTER
    SITUACAO CHAR(1) NOT NULL, -- 'A' ou 'I' (Ativo / Inativo)
    SENHA VARCHAR(200) NOT NULL, 	
    FOREIGN KEY(ID_PERMISSAO) REFERENCES PERMISSAO (ID),
    CONSTRAINT USUARIO_PK PRIMARY KEY (ID)
);

CREATE INDEX INDICE_COLABORADOR ON COLABORADOR (ID_PERMISSAO);

ALTER TABLE COLABORADOR
ADD CONSTRAINT EMAIL_UNIQUE UNIQUE (EMAIL);

CREATE TABLE FEITO(
    ID NUMBER(12) NOT NULL,
    NOME VARCHAR2(200) NOT NULL,
    DESCRICAO VARCHAR2(200) NOT NULL,
    DESCRICAORESUMIDA VARCHAR2(100) NULL,
    ID_PERMISSAO NUMBER(12) NOT NULL,
    IMAGEM VARCHAR2(500) NOT NULL,
    RELEVANCIA NUMBER(1) NOT NULL,
    FOREIGN KEY(ID_PERMISSAO) REFERENCES PERMISSAO (ID),
    CONSTRAINT FEITO_PK PRIMARY KEY (ID)
);

CREATE INDEX INDICE_FEITO ON FEITO(ID_PERMISSAO);

CREATE TABLE COLABORADOR_FEITO(
    ID NUMBER(12) NOT NULL,
    ID_COLABORADOR NUMBER(12) NOT NULL,
    ID_FEITO NUMBER(12) NOT NULL,
    DATAFEITO DATE NOT NULL,
    OBSERVACAO VARCHAR2(200) NULL,
    FOREIGN KEY(ID_COLABORADOR) REFERENCES COLABORADOR (ID),
    FOREIGN KEY(ID_FEITO) REFERENCES FEITO (ID),
    CONSTRAINT COLABORADORFEITO_PK PRIMARY KEY (ID)
);

CREATE INDEX INDICE_COLABORADOR_FEITO ON COLABORADOR_FEITO (ID_COLABORADOR,ID_FEITO);

CREATE TABLE SOLICITACAO_ACESSO(
	ID NUMBER(12) NOT NULL,
    ID_COLABORADOR NUMBER(12) NOT NULL,
	FOREIGN KEY(ID_COLABORADOR) REFERENCES COLABORADOR (ID),
    CONSTRAINT SOLICITACAOACESSO_PK PRIMARY KEY (ID)
);

CREATE INDEX INDICE_SOLICITACAO_ACESSO ON SOLICITACAO_ACESSO(ID_COLABORADOR);

CREATE TABLE TIMECWI(
    ID NUMBER(12) NOT NULL,
    NOME VARCHAR2(200) NOT NULL,
    DESCRICAO VARCHAR2(500) NOT NULL,
    DESCRICAORESUMIDA VARCHAR2(100),
    SITUACAO CHAR(1), -- 'A' ou 'I' / Ativou ou Inativo 
    CONSTRAINT TIMECWI_PK PRIMARY KEY (ID)
);

CREATE TABLE TIMECWI_COLABORADOR(
    ID NUMBER(12) NOT NULL,
    ID_TIMECWI NUMBER(12) NOT NULL,
    ID_COLABORADOR NUMBER(12) NOT NULL,
    TIPO CHAR(1) NOT NULL, --'O' ou 'M' / Owner ou Membro
    FOREIGN KEY(ID_TIMECWI) REFERENCES TIMECWI (ID),
    FOREIGN KEY(ID_COLABORADOR) REFERENCES COLABORADOR (ID),
    CONSTRAINT TIMECWICOLABORADOR_PK PRIMARY KEY (ID)
);

CREATE INDEX INDICE_TIMECWI_COLABORADOR ON COLABORADOR_FEITO(ID_TIMECWI,ID_COLABORADOR);

CREATE TABLE COLABORADOR_TAG(
    ID NUMBER(12) NOT NULL,
    ID_COLABORADOR NUMBER(12) NOT NULL,
    DESCRICAO VARCHAR2(20) NOT NULL,
    FOREIGN KEY(ID_COLABORADOR) REFERENCES TIME (ID),
    CONSTRAINT COLABORADORTAG_PK PRIMARY KEY (ID)
);

CREATE INDEX INDICE_COLABORADOR_TAG ON COLABORADOR_TAG (ID_COLABORADOR);

CREATE TABLE COLABORADOR_REACAO_TAG(
    ID NUMBER(12) NOT NULL,
    ID_COLABORADORTAG NUMBER(12) NOT NULL,
    ID_COLABORADOR NUMBER(12) NOT NULL,
    REACAO CHAR(1) NOT NULL, -- 'C' ou 'D' / Concordou ou Discordou
    FOREIGN KEY(ID_COLABORADORTAG) REFERENCES CLABORADOR_TAG (ID),
    FOREIGN KEY(ID_COLABORADOR) REFERENCES COLABORADOR (ID),
    CONSTRAINT COLABORADORTAG_PK PRIMARY KEY (ID)
);

CREATE INDEX INDICE_COLABORADOR_REACAO_TAG ON COLABORADOR_REACAO_TAG (ID_COLABORADORTAG,ID_COLABORADOR);